name: Check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  cancel-previous-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: randy3k/gh-actions/cancel-previous-runs@main

  check:
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    steps:
      - uses: actions/checkout@v2
      - uses: randy3k/gh-actions/r-check@main
        with:
          r-version: ${{ matrix.config.r }}

  coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: randy3k/gh-actions/r-coverage@main
