name: Main

on: [push, pull_request]

jobs:
  rchk:
    if: contains(github.event.head_commit.message, '[ci skip]') == false
    runs-on: ubuntu-latest
    env:
      NOT_CRAN: true
      _R_CHECK_CRAN_INCOMING_: false
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/run-rchk@master
      # - uses: randy3k/actions/run-rchk@rchk

  ubsan:
    if: contains(github.event.head_commit.message, '[ci skip]') == false
    runs-on: ubuntu-latest
    container: rocker/r-devel-ubsan-clang
    env:
      NOT_CRAN: true
      _R_CHECK_CRAN_INCOMING_: false
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          Rscript -e "install.packages(c('remotes', 'rcmdcheck'), repos = 'https://cloud.r-project.org')"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"
      - name: Running Tests
        run: |
          Rscript -e "rcmdcheck::rcmdcheck(args = c('--as-cran', '--no-manual', '--timings'), error_on = 'warning')"

  linux:
    if: contains(github.event.head_commit.message, '[ci skip]') == false
    strategy:
      matrix:
        r: [latest]
        # r: [3.5, latest, devel]
    runs-on: ubuntu-latest
    container: rocker/tidyverse:${{ matrix.r }}
    env:
      NOT_CRAN: true
      _R_CHECK_CRAN_INCOMING_: false
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          Rscript -e "install.packages(c('remotes', 'rcmdcheck'), repos = 'https://cloud.r-project.org')"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"
      - name: Running Tests
        run: |
          Rscript -e "rcmdcheck::rcmdcheck(args = c('--as-cran', '--no-manual', '--timings'), error_on = 'warning')"
      - name: Codecov
        run: Rscript -e "covr::codecov()"
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

  macos:
    if: contains(github.event.head_commit.message, '[ci skip]') == false
    strategy:
      matrix:
        r: [3.6]
        # r: [3.5, 3.6, devel]
    runs-on: macOS-latest
    env:
      NOT_CRAN: true
      _R_CHECK_CRAN_INCOMING_: false
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r }}
      - name: Install dependencies
        run: |
          Rscript -e "install.packages(c('remotes', 'rcmdcheck'), repos = 'https://cloud.r-project.org', type = 'mac.binary.el-capitan')"
          Rscript -e "remotes::install_deps(dependencies = TRUE, type = 'mac.binary.el-capitan')"
      - name: Running Tests
        run: |
          Rscript -e "rcmdcheck::rcmdcheck(args = c('--as-cran', '--no-manual', '--timings'), error_on = 'warning')"
      - name: Codecov
        run: Rscript -e "covr::codecov()"
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

  windows:
    if: contains(github.event.head_commit.message, '[ci skip]') == false
    strategy:
      matrix:
        r: [3.6]
        # r: [3.5, 3.6, devel]
    runs-on: windows-latest
    env:
      NOT_CRAN: true
      _R_CHECK_CRAN_INCOMING_: false
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r }}
      - name: Install dependencies
        run: |
          Rscript -e "install.packages(c('remotes', 'rcmdcheck'), repos = 'https://cloud.r-project.org', type = 'win.binary')"
          Rscript -e "remotes::install_deps(dependencies = TRUE, type = 'win.binary')"
      - name: Running Tests
        run: |
          Rscript -e "rcmdcheck::rcmdcheck(args = c('--as-cran', '--no-manual', '--timings'), error_on = 'warning')"
      - name: Codecov
        run: Rscript -e "covr::codecov()"
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
