name: build

on: [push]

jobs:
  rchk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: randy3k/github-action-rchk@master
      env:
        NOT_CRAN: true

  ubsan:
    runs-on: ubuntu-latest
    container: rocker/r-devel-ubsan-clang
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        Rscript -e "install.packages(c('remotes', 'rcmdcheck'), repos = 'https://cloud.r-project.org')"
        Rscript -e "remotes::install_deps(dependencies = TRUE)"
      shell:
        bash
    - name: Running Tests
      run: |
        Rscript -e "rcmdcheck::rcmdcheck(args = c('--as-cran', '--no-manual', '--timings'), error_on = 'warning')"
      env:
        NOT_CRAN: true
      shell:
        bash

  linux:
    strategy:
      matrix:
        r: [latest]
        # r: [3.5, latest, devel]
    runs-on: ubuntu-latest
    container: rocker/tidyverse:${{ matrix.r }}
    steps:
    - uses: actions/checkout@v1
    - name: Install apt-get dependencies
      run: |
        apt-get update
        apt-get install git ssh curl bzip2 libffi6 libffi-dev -y
    - name: Install dependencies
      run: |
        Rscript -e "install.packages(c('remotes', 'rcmdcheck'), repos = 'https://cloud.r-project.org')"
        Rscript -e "remotes::install_deps(dependencies = TRUE)"
      shell:
        bash
    - name: Running Tests
      run: |
        Rscript -e "rcmdcheck::rcmdcheck(args = c('--as-cran', '--no-manual', '--timings'), error_on = 'warning')"
      env:
        NOT_CRAN: true
      shell:
        bash
    - name: Codecov
      run: Rscript -e "covr::codecov()"
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
      shell:
        bash

  macos:
    strategy:
      matrix:
        r: [3.6]
        # r: [3.5, 3.6, devel]
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: ${{ matrix.r }}
    - name: Install dependencies
      run: |
        Rscript -e "install.packages(c('remotes', 'rcmdcheck'), repos = 'https://cloud.r-project.org', type = 'mac.binary.el-capitan')"
        Rscript -e "remotes::install_deps(dependencies = TRUE, type = 'mac.binary.el-capitan')"
      shell:
        bash
    - name: Running Tests
      run: |
        Rscript -e "rcmdcheck::rcmdcheck(args = c('--as-cran', '--no-manual', '--timings'), error_on = 'warning')"
      env:
        NOT_CRAN: true
      shell:
        bash
    - name: Codecov
      run: Rscript -e "covr::codecov()"
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
      shell:
        bash

  windows:
    strategy:
      matrix:
        r: [3.6]
        # r: [3.5, 3.6, devel]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: ${{ matrix.r }}
    - name: Install dependencies
      run: |
        Rscript -e "install.packages(c('remotes', 'rcmdcheck'), repos = 'https://cloud.r-project.org', type = 'win.binary')"
        Rscript -e "remotes::install_deps(dependencies = TRUE, type = 'win.binary')"
      shell:
        pwsh
    - name: Running Tests
      run: |
        Rscript -e "rcmdcheck::rcmdcheck(args = c('--as-cran', '--no-manual', '--timings'), error_on = 'warning')"
      env:
        NOT_CRAN: true
      shell:
        pwsh
    - name: Codecov
      run: Rscript -e "covr::codecov()"
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
      shell:
        pwsh
