on:
  schedule:
    # every six hour
    - cron: 0 */6 * * *
jobs:
  publish-github-release:
    runs-on: ubuntu-latest
    container: rtagbot/tagbot:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: fetch all tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: check and publish release
        run: |
          tagbot::publish_release()
        shell: Rscript {0}
