name: TagBot

on:
  pull_request:
    branches: [main, master]

jobs:
  publish-github-release:
    runs-on: ubuntu-latest
    container: rtagbot/tagbot:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: check and publish release
        run: |
          tagbot::publish_release()
        shell: Rscript {0}
        env:
          GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
